baseURL: https://todogroup.org
contentDir: content/en
enableRobotsTXT: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
rssLimit: 1
outputs:
  home: ["HTML", "Atom"]
mediaTypes:
  "application/atom":
    suffixes: [xml]

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: feed
    isPlainText: false

# Internationalization
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

# Disable non-English languages (for now)
disableLanguages:
- zh
- ko

languages:
  en:
    languageName: English
    title: "// TODO: Talk openly, develop openly"
    weight: 1
    description: "TODO: talk openly, develop openly. We believe we can better improve our open source programs - and our contributions to the open source movement as a whole - by working together."
    longTitle: "TODO Group // TODO: Talk openly, develop openly"
    footer:
    - title: Home
      link: /
    - title: Blog
      link: /blog
    - title: Guides
      link: /guides
    - title: About
      link: /about
    - title: Community
      link: /community
    - title: Members
      link: /members
    - title: Join
      link: /join
    - title: Q&A
      link: /faq
  zh:
    languageName: CHINESE
    title: SHORT CHINESE TITLE
    weight: 2
    longTitle: LONGER CHINESE TITLE
    description: SHORT DESCRIPTION IN CHINESE
    footer:
    - title: HOME IN CHINESE
      link: /zh
    - title: ABOUT IN CHINESE
      link: /zh/about
  ko:
    languageName: KOREAN
    title: SHORT KOREAN TITLE
    weight: 3
    longTitle: LONGER KOREAN TITLE
    description: SHORT DESCRIPTION IN KOREAN
    footer:
    - title: HOME IN KOREAN
      link: /ko
    - title: ABOUT IN KOREAN
      link: /ko/about


params:
  googleAnalytics:
    id: UA-54779798-1
  keywords:
  - open source
  - todo
  - talk openly
  - develop openly
  - high quality

  slack:
    channel: todogroup
